### ISSUE TITLE
Invalid api key

### ISSUE THREAD

**Issue by naveen1hot** [fugkco/script.elementum.jackett#15]
Hi @fugkco 
Thanks for your effort and work. But I'm unable to use thus add-on getting error as invalid api key. Could you pls kindly tell me the resolution/guide pls

**Comment by fugkco** [comment]
Have you updated the settings to add the api key?

**Comment by naveen1hot** [comment]
Thanks for your quik response. Could you kindly help on What settings need to do?? Pls

**Comment by SubEdict** [comment]
Hi there, How/from **where do I get API Key** to the setting? This info is missing.

Just installed, usually using Elementum+Burst (for years), but lately, rarbg won't fetch and I'm looking for an alternative.
Will Jackett fetch results from rarbg? if so, what do I do in the setting?

Any help to get started will do.

**Comment by fugkco** [comment]
This is for use with Jackett. You need to set up Jackett separately, which will give you an API key. This is out of the scope of this project. Please search online on how to do that.

**Comment by SubEdict** [comment]
> for use **with** Jackett. You need to set up Jackett **separately**,

Aha, sorry, for a second, I thought it's a Kodi add-on program merges into Elementum like Burst.
My bad, got it. ><

**Comment by fugkco** [comment]
Your understanding is correct. The difference between this and Burst is that this addon utilizes Jackett to scrape torrent sites, whereas Elementum Burst has its own scrapers.

**Comment by SubEdict** [comment]
Update: [Install and tested](https://imgur.com/a/98BIsEE) to see if rarbg will fetch results. Unfortunately, like Burst, it didn't work either (Getting results from all except rarbg).

BTW, I see that the API key is instant create at the first launch, and no need to change or update anything. ...yes?
