### ISSUE TITLE
change colors of providers

### ISSUE THREAD

**Issue by ShlomiD83** [fugkco/script.elementum.jackett#16]
Hi,
I've just only found out about this addon, 99% of the time it works great, thanks!

Is is possible to change colors of the provider's name in the results page?
RARBG is shown in green, I would like to have the option to change it to blue.

is that possible like in Burst?

Thanks!

**Comment by fugkco** [comment]
Dunno, I feel like this should be something that Jackett should return. If they implement it, I'd be happy to add support. The only reason I added colours is that it wasn't entirely clear where the different results came from. Adding options to make this customizable will mean a lot of work. I suggest you raise this as an issue and/or PR in the [Jackett](https://github.com/Jackett/Jackett) repo. Once done, I can add support here.

**Comment by ShlomiD83** [comment]
https://github.com/linuxserver/docker-jackett

You mean raise a PR here?

**Comment by fugkco** [comment]
I linked it in my previous comment, raise a feature request or a PR [here](https://github.com/Jackett/Jackett)

**Comment by fugkco** [comment]
Sorry, I meant [here](https://github.com/Jackett/Jackett)

**Comment by ShlomiD83** [comment]
That's a link to an app called Cardigann, are you sure?

**Comment by fugkco** [comment]
I've fixed the link!

**Comment by ShlomiD83** [comment]
OK, open it there even tho I'm using the linuxserver docker image?

**Comment by fugkco** [comment]
I've [raised a ticket](https://github.com/Jackett/Jackett/issues/14363) for you. Please follow progress there.

**Comment by ShlomiD83** [comment]
> I've [raised a ticket](https://github.com/Jackett/Jackett/issues/14363) for you. Please follow progress there.

Thank you very much.
Very appreciated.

**Comment by ShlomiD83** [comment]
They rejected my request, any change you reconsider implementing colors for at least the most popular providers?

**Comment by fugkco** [comment]
I've no desire to implement it, but happy to merge a PR if someone raises one!

**Comment by ShlomiD83** [comment]
RARBG closed it's doors and most of the other popular providers doesn't work at all.
so I guess this doesn't matter anymore.
