### ISSUE TITLE
version 2.0.2 not working

### ISSUE THREAD

**Issue by ShlomiD83** [fugkco/script.elementum.jackett#18]
After updating to version 2.0.2 the plugin throws an error when searching for a movie/tv show.
it complains about an attribute error.

here's my log: https://rentry.co/n2yxh
![Screenshot 2023-05-29 082656](https://github.com/fugkco/script.elementum.jackett/assets/17053215/37327d55-835b-41d0-a06d-7753e618b1bb)
![Screenshot 2023-05-29 082701](https://github.com/fugkco/script.elementum.jackett/assets/17053215/818d7434-485b-4fbf-96c3-2dc522d8354a)

**Comment by fugkco** [comment]
Can you please enable debug logging in kodi, and send upload those logs?

Besides that, please downgrade for now. Will try and address this later today.

**Comment by ShlomiD83** [comment]
The log I've uploaded is in debug mode.
