### ISSUE TITLE
Invalid api key

### ISSUE THREAD

**Issue by naveen1hot** [fugkco/script.elementum.jackett#30]
Hello @fugkco ,
I have installed jackett with elementum. But I getting error as invalid api key. How I can get that or how to fix this. Many thanks for your support..

**Comment by JulioQc** [comment]
did you even configure the api key in plugin settings?

**Comment by antonsoroko** [comment]
it is expected that if you know about Jackett then you also know that you need to install it
https://github.com/Jackett/Jackett (see installation steps)
or find a public Jackett in internet.

script.elementum.jackett is just a "broker" between elementum and jackett.

**Comment by fugkco** [comment]
Yes, you need to set up Jackett and input the API key in this addon's settings. Closing as there's no response from OP. Feel free to comment, I'll be happy to re-open.
