### ISSUE TITLE
Public parsers with no API key?

### ISSUE THREAD

**Issue by szur77** [fugkco/script.elementum.jackett#35]
Dear fugkco,

Is it possible to use your script with public parsers, such as jacred.xyz or torrentio.strem.fun, both of which do not provide API keys? Looks like at the moment it's a required field... 

Thank you.

**Comment by fugkco** [comment]
Neither of those seem to be jackett endpoints. I don't have the time nor the motivation to implement them as a backend. Besides, they'd really need to be a separate addon.
