### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u200b' in position 32: ordinal not in range(128)

### ISSUE THREAD

**Issue by dairefagan** [fugkco/script.elementum.jackett#5]
I think I have only seen this error when searching for a title with a letter that has an accent over it but I cannot remember all of the shows, what I do know is that someone here searched for 90 Day Fiancé a few weeks ago. and I have now reproduced this with the following:

1. _Elementum >> TV Shows >> Search >> New Search >> 90 Day Fiancé_

2. _Select S01E01_

This results in an error matching the subject of this ticket, and the user is returned to the episode selection screen.

The last entry in the Jackett WebUI log is:

`2020-09-23 17:58:29 Info Found 118 releases from AggregateSearch for : 90 day fiancé S01E01`

Manuall searching through the WebUI returns 21 filtered entries. They seem to actually be for spin off shows of the original, but nevertheless, they appear without error.

I have turned on Addons >> Elementum Jackett >> Advanced >> Enable but not been able to display a deb log in Brave Browser with variations of 127.0.0.1:5678, 192.168.1.5:5678, localhost:5678, please let me know if I need to do something else to access it.

Please find Elementum debugging log, including the Kodi log, both with debugging enabled here: [](http://paste.kodi.tv/yekeweyipa)

Ubuntu 20.04.1 & Nvidia Shield Android TV
Kodi 18.8
Jackett 0.16.1307.0 running on Raspberry Pi 3
Elementum 0.1.58
Elementum Jackett *beta 1

*I am using the beta version from two or three days ago. I see from an md5sum the beta 1 in releases is different to the current beta 1*

**Comment by fugkco** [comment]
Hi I think you forgot to upload the logs. I will have a test this out soon myself, but in case I can't reproduce it, I will need the logs.

**Comment by chicungunya** [comment]
Hello I have the same problem but it's because the accent : Fiancé 

Is that possible to add special character to your script ?

Thanks a lot !

**Comment by fugkco** [comment]
I believe this isn't an issue any more with the latest versions.
