### ISSUE TITLE
Jackett search

### ISSUE THREAD

**Issue by kovacicjanez** [fugkco/script.elementum.jackett#6]
Hi,

When searcing for movie Jackett returns only torrents from one Indexer (in my case only YTS Indexer).
I also have 1337x and RARBG and other Indexers... why elementum found only YTS torrents?
[log.txt](https://github.com/fugkco/script.elementum.jackett/files/5446481/log.txt)

**Comment by kovacicjanez** [comment]
I found out if I play from my Library.. than only one provider returns torrents (like 4 torrents)
If I play in Extended Info Script (browse movies....) than at least 200 torrents are returned for the same movie I have in my library

why is that?

**Comment by kovacicjanez** [comment]
.. found problem..

**Comment by chicungunya** [comment]
@kovacicjanez I have the same problem. I have 2 providers on Jackett, both are working but sometimes for movies really known I have only results from 1 provider. What is your solution ? 
Thanks !

**Comment by kovacicjanez** [comment]
If you play via context menu (elementum play) than it works (it uses name shown in kodi for search).
you must have context.elementum installed.

**Comment by chicungunya** [comment]
I'm sorry but I don't really understand. I have just installed context.elementum but what do you mean by "elementum play" ?  I use only kodi, and not the web ui of elementum. Is that correct ?

**Comment by kovacicjanez** [comment]
in kodi open "context menu" in that menu you have option "elementum play"

After highlighting an item (eg a movie) the Context Menu can be invoked by:

long press the OK key
Press letter C on a keyboard
right-clicking with the mouse

**Comment by chicungunya** [comment]
Thanks a lot but when I click on Elementum Play, no link founded with Jackett. Do I have to do something else ?

**Comment by kovacicjanez** [comment]
provide jackett log and elementum log and I can check

**Comment by chicungunya** [comment]
I have this on Jackett : Heartbeat took longer than "00:00:01" at "12/08/2020 00:12:11 +00:00". This could be caused by thread pool starvation. 
Maybe I have to increase the search time somewhere ? 
Thanks !

**Comment by chicungunya** [comment]
> provide jackett log and elementum log and I can check

@kovacicjanez @fugkco 
It's working now but I have problem with Tv shows 
For example, if I choose Elementum Play for episode 1 of a show, it will search just _episode 1_ in Jackett and not : _my show s01e01_ so the results are totally false

Do you have the same problem ?

(I use Trakt and TheMovieDB Helper)
Thanks
